cameras:
- id: cam-1_rtsp_1770917682
  name: cam-1
  source: rtsp://admin:L2CD8412@192.168.0.103:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
  camera_type: rtsp
  fps: 30
  resolution: 640x480
  status: online
  processing_active: false
  processing_type: null
  processing_params: {}
  created_at: '2026-02-12T17:34:42.774322'
  updated_at: '2026-02-24T14:07:29.988565'
- id: cam-2_webcam_1770921408
  name: cam-2
  source: '0'
  camera_type: webcam
  fps: 30
  resolution: 640x480
  status: offline
  processing_active: false
  processing_type: null
  processing_params: {}
  created_at: '2026-02-12T18:36:48.156743'
  updated_at: '2026-02-24T06:40:23.931155'
- id: cam3_webcam_1771887423
  name: cam3
  source: '0'
  camera_type: webcam
  fps: 30
  resolution: 640x480
  status: offline
  processing_active: false
  processing_type: null
  processing_params: {}
  created_at: '2026-02-23T22:57:03.300029'
  updated_at: '2026-02-24T00:24:14.881787'
