system:
  live_stream_mode: mjpeg
  uvicorn_reload: true
  low_power_mode: false
  sensitivity: 4
  jpeg_quality: 70
  pipe_buffer_size: 100000000
  max_vel: 0.1
  bg_diff: 50
  max_clip_length: 60
  motion_check_interval: 10
  min_free_storage_bytes: 1073741824
  rtsp_unified_demux_enabled: false
