cameras:
- id: cam-1_rtsp_1770917682
  name: cam-1
  source: rtsp://admin:L2CD8412@192.168.0.103:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
  camera_type: rtsp
  fps: 5
  resolution: 640x480
  status: offline
  processing_active: false
  processing_type: null
  processing_params: {}
  created_at: '2026-02-12T17:34:42.774322'
  updated_at: '2026-03-23T16:12:32.969043'
  audio_enabled: false
  audio_source: null
  audio_input_format: null
  audio_sample_rate: 16000
  audio_chunk_size: 512
- id: cam-2_webcam_1770921408
  name: cam-2
  source: '0'
  camera_type: webcam
  fps: 5
  resolution: 640x480
  status: offline
  processing_active: false
  processing_type: null
  processing_params: {}
  created_at: '2026-02-12T18:36:48.156743'
  updated_at: '2026-03-23T16:12:43.955915'
  audio_enabled: false
  audio_source: default
  audio_input_format: pulse
  audio_sample_rate: 16000
  audio_chunk_size: 512
- id: cam3_webcam_1771887423
  name: cam3
  source: rtsp://admin:L2D841A1@192.168.2.131:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
  camera_type: rtsp
  fps: 15
  resolution: 640x480
  status: offline
  processing_active: false
  processing_type: null
  processing_params: {}
  created_at: '2026-02-23T22:57:03.300029'
  updated_at: '2026-03-26T17:25:33.639492'
  audio_enabled: true
  audio_source: rtsp://admin:L2D841A1@192.168.2.131:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
  audio_input_format: rtsp
  audio_sample_rate: 16000
  audio_chunk_size: 512
- id: rec-1_recorded_1774432011
  name: rec-1
  source: /root/Motion-Analysis-Server/api/recordings/train_mot20_01.mp4
  camera_type: recorded
  fps: 30
  resolution: 1920x1080
  status: offline
  audio_enabled: false
  audio_source: default
  audio_input_format: pulse
  audio_sample_rate: 16000
  audio_chunk_size: 512
  processing_active: false
  processing_type: null
  processing_params: {}
  created_at: '2026-03-25T09:46:51.183380'
  updated_at: '2026-03-26T16:12:39.113294'
